name: Cloud Build Notifier
on:
  pull_request_target:
    branches:
      - master
jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"